// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/broker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConsumerGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerGroup) Reset() {
	*x = ConsumerGroup{}
	mi := &file_proto_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerGroup) ProtoMessage() {}

func (x *ConsumerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerGroup.ProtoReflect.Descriptor instead.
func (*ConsumerGroup) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumerGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConsumerGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateConsumerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConsumerGroupRequest) Reset() {
	*x = CreateConsumerGroupRequest{}
	mi := &file_proto_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsumerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerGroupRequest) ProtoMessage() {}

func (x *CreateConsumerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateConsumerGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConsumerGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Subscription struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TopicId         int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	ConsumerGroupId int64                  `protobuf:"varint,2,opt,name=consumer_group_id,json=consumerGroupId,proto3" json:"consumer_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Subscription) GetConsumerGroupId() int64 {
	if x != nil {
		return x.ConsumerGroupId
	}
	return 0
}

type CreateSubscriptionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TopicName string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	// Optional: if empty, the subscription is created against the default
	// consumer group.
	ConsumerGroupName string `protobuf:"bytes,2,opt,name=consumer_group_name,json=consumerGroupName,proto3" json:"consumer_group_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_proto_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubscriptionRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetConsumerGroupName() string {
	if x != nil {
		return x.ConsumerGroupName
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{6}
}

func (x *PublishRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *PublishRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{7}
}

func (x *PublishResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type RegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroupName string                 `protobuf:"bytes,1,opt,name=consumer_group_name,json=consumerGroupName,proto3" json:"consumer_group_name,omitempty"`
	ConsumerName      string                 `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetConsumerGroupName() string {
	if x != nil {
		return x.ConsumerGroupName
	}
	return ""
}

func (x *RegisterRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{9}
}

func (x *AckRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ConsumeClientMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ConsumeClientMsg_Register
	//	*ConsumeClientMsg_Ack
	Kind          isConsumeClientMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeClientMsg) Reset() {
	*x = ConsumeClientMsg{}
	mi := &file_proto_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeClientMsg) ProtoMessage() {}

func (x *ConsumeClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeClientMsg.ProtoReflect.Descriptor instead.
func (*ConsumeClientMsg) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeClientMsg) GetKind() isConsumeClientMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ConsumeClientMsg) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Kind.(*ConsumeClientMsg_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ConsumeClientMsg) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Kind.(*ConsumeClientMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isConsumeClientMsg_Kind interface {
	isConsumeClientMsg_Kind()
}

type ConsumeClientMsg_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ConsumeClientMsg_Ack struct {
	Ack *AckRequest `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ConsumeClientMsg_Register) isConsumeClientMsg_Kind() {}

func (*ConsumeClientMsg_Ack) isConsumeClientMsg_Kind() {}

type MessageDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	DeliveryCount int32                  `protobuf:"varint,4,opt,name=delivery_count,json=deliveryCount,proto3" json:"delivery_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDelivery) Reset() {
	*x = MessageDelivery{}
	mi := &file_proto_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelivery) ProtoMessage() {}

func (x *MessageDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelivery.ProtoReflect.Descriptor instead.
func (*MessageDelivery) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{11}
}

func (x *MessageDelivery) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageDelivery) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *MessageDelivery) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageDelivery) GetDeliveryCount() int32 {
	if x != nil {
		return x.DeliveryCount
	}
	return 0
}

type ConsumeServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ConsumeServerMsg_Message
	Kind          isConsumeServerMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeServerMsg) Reset() {
	*x = ConsumeServerMsg{}
	mi := &file_proto_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeServerMsg) ProtoMessage() {}

func (x *ConsumeServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeServerMsg.ProtoReflect.Descriptor instead.
func (*ConsumeServerMsg) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumeServerMsg) GetKind() isConsumeServerMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ConsumeServerMsg) GetMessage() *MessageDelivery {
	if x != nil {
		if x, ok := x.Kind.(*ConsumeServerMsg_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isConsumeServerMsg_Kind interface {
	isConsumeServerMsg_Kind()
}

type ConsumeServerMsg_Message struct {
	Message *MessageDelivery `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

func (*ConsumeServerMsg_Message) isConsumeServerMsg_Kind() {}

var File_proto_broker_proto protoreflect.FileDescriptor

const file_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/broker.proto\x12\x06broker\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\rConsumerGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"0\n" +
	"\x1aCreateConsumerGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"U\n" +
	"\fSubscription\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12*\n" +
	"\x11consumer_group_id\x18\x02 \x01(\x03R\x0fconsumerGroupId\"j\n" +
	"\x19CreateSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12.\n" +
	"\x13consumer_group_name\x18\x02 \x01(\tR\x11consumerGroupName\"I\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"0\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"f\n" +
	"\x0fRegisterRequest\x12.\n" +
	"\x13consumer_group_name\x18\x01 \x01(\tR\x11consumerGroupName\x12#\n" +
	"\rconsumer_name\x18\x02 \x01(\tR\fconsumerName\"+\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"y\n" +
	"\x10ConsumeClientMsg\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x17.broker.RegisterRequestH\x00R\bregister\x12&\n" +
	"\x03ack\x18\x02 \x01(\v2\x12.broker.AckRequestH\x00R\x03ackB\x06\n" +
	"\x04kind\"\x90\x01\n" +
	"\x0fMessageDelivery\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12%\n" +
	"\x0edelivery_count\x18\x04 \x01(\x05R\rdeliveryCount\"O\n" +
	"\x10ConsumeServerMsg\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x17.broker.MessageDeliveryH\x00R\amessageB\x06\n" +
	"\x04kind2\xe2\x02\n" +
	"\x06Broker\x128\n" +
	"\vCreateTopic\x12\x1a.broker.CreateTopicRequest\x1a\r.broker.Topic\x12P\n" +
	"\x13CreateConsumerGroup\x12\".broker.CreateConsumerGroupRequest\x1a\x15.broker.ConsumerGroup\x12M\n" +
	"\x12CreateSubscription\x12!.broker.CreateSubscriptionRequest\x1a\x14.broker.Subscription\x12:\n" +
	"\aPublish\x12\x16.broker.PublishRequest\x1a\x17.broker.PublishResponse\x12A\n" +
	"\aConsume\x12\x18.broker.ConsumeClientMsg\x1a\x18.broker.ConsumeServerMsg(\x010\x01B\x15Z\x13messagebroker/protob\x06proto3"

var (
	file_proto_broker_proto_rawDescOnce sync.Once
	file_proto_broker_proto_rawDescData []byte
)

func file_proto_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)))
	})
	return file_proto_broker_proto_rawDescData
}

var file_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_broker_proto_goTypes = []any{
	(*Topic)(nil),                      // 0: broker.Topic
	(*CreateTopicRequest)(nil),         // 1: broker.CreateTopicRequest
	(*ConsumerGroup)(nil),              // 2: broker.ConsumerGroup
	(*CreateConsumerGroupRequest)(nil), // 3: broker.CreateConsumerGroupRequest
	(*Subscription)(nil),               // 4: broker.Subscription
	(*CreateSubscriptionRequest)(nil),  // 5: broker.CreateSubscriptionRequest
	(*PublishRequest)(nil),             // 6: broker.PublishRequest
	(*PublishResponse)(nil),            // 7: broker.PublishResponse
	(*RegisterRequest)(nil),            // 8: broker.RegisterRequest
	(*AckRequest)(nil),                 // 9: broker.AckRequest
	(*ConsumeClientMsg)(nil),           // 10: broker.ConsumeClientMsg
	(*MessageDelivery)(nil),            // 11: broker.MessageDelivery
	(*ConsumeServerMsg)(nil),           // 12: broker.ConsumeServerMsg
}
var file_proto_broker_proto_depIdxs = []int32{
	8,  // 0: broker.ConsumeClientMsg.register:type_name -> broker.RegisterRequest
	9,  // 1: broker.ConsumeClientMsg.ack:type_name -> broker.AckRequest
	11, // 2: broker.ConsumeServerMsg.message:type_name -> broker.MessageDelivery
	1,  // 3: broker.Broker.CreateTopic:input_type -> broker.CreateTopicRequest
	3,  // 4: broker.Broker.CreateConsumerGroup:input_type -> broker.CreateConsumerGroupRequest
	5,  // 5: broker.Broker.CreateSubscription:input_type -> broker.CreateSubscriptionRequest
	6,  // 6: broker.Broker.Publish:input_type -> broker.PublishRequest
	10, // 7: broker.Broker.Consume:input_type -> broker.ConsumeClientMsg
	0,  // 8: broker.Broker.CreateTopic:output_type -> broker.Topic
	2,  // 9: broker.Broker.CreateConsumerGroup:output_type -> broker.ConsumerGroup
	4,  // 10: broker.Broker.CreateSubscription:output_type -> broker.Subscription
	7,  // 11: broker.Broker.Publish:output_type -> broker.PublishResponse
	12, // 12: broker.Broker.Consume:output_type -> broker.ConsumeServerMsg
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_broker_proto_init() }
func file_proto_broker_proto_init() {
	if File_proto_broker_proto != nil {
		return
	}
	file_proto_broker_proto_msgTypes[10].OneofWrappers = []any{
		(*ConsumeClientMsg_Register)(nil),
		(*ConsumeClientMsg_Ack)(nil),
	}
	file_proto_broker_proto_msgTypes[12].OneofWrappers = []any{
		(*ConsumeServerMsg_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_proto_depIdxs,
		MessageInfos:      file_proto_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_proto = out.File
	file_proto_broker_proto_goTypes = nil
	file_proto_broker_proto_depIdxs = nil
}
